server:
  port: 8099
  servlet:
    context-path: /blog
spring:
  profiles:
    active: dev
  application:
    name: hibiscus-blog
mybatis:
  mapper-locations: classpath*:mapper/*/*Mapper.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql